<a href="https://colab.research.google.com/github/EUNJIKIM810/test/blob/main/pytorch_tutorial_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

**<텐서 초기화>**

데이터로부터 직접(directly) 생성하기

In [16]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


NumPy 배열로부터 생성하기

In [17]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


다른 텐서로부터 생성하기:

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.

In [14]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1871, 0.9739],
        [0.9828, 0.5963]]) 



무작위(random) 또는 상수(constant) 값을 사용하기:

shape 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [18]:
shape = (2,3,) #2행 3열 형태의 2차원 텐서를 만든다
rand_tensor = torch.rand(shape) #텐서를 무작위로 채운다
ones_tensor = torch.ones(shape) #텐서를 1로 채운다
zeros_tensor = torch.zeros(shape) #텐서를 0으로 채운다

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3818, 0.3254, 0.3226],
        [0.4811, 0.1552, 0.7554]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**텐서의 속성(Attribute)**

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.


In [19]:
tensor = torch.rand(3,4) #3행 4열의 2차원 텐서를 무작위로 초기화한다.

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**텐서 연산(Operation)**

기본적으로 텐서는 CPU에 생성됩니다. .to 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있습니다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하세요!

In [20]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

NumPy식의 표준 인덱싱과 슬라이싱:

In [21]:
tensor = torch.ones(4, 4) #모든 값이 1로 초기화된 4행 4열 형태의 텐서를 만든다
print(f"First row: {tensor[0]}") #텐서의 첫번쨰 행 조회하기. 파이썬 인덱싱은 0부터 시작하므로 첫번쨰 행을 의미한다.
print(f"First column: {tensor[:, 0]}") #텐서의 첫번째 열 조회하기.
#:는 텐서의 모든 행을 선택하라는 뜻이고, 0은 첫 번째 열을 선택하라는 뜻

print(f"Last column: {tensor[..., -1]}") #텐서의 마지막 열 조회하기
#...은 모든 차원을 그대로 유지하라는 의미이며, -1은 마지막 요소를 선택하라는 뜻
tensor[:,1] = 0 #두번째 열의 값을 모두 0으로 수정
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


torch.ones() 함수로 생성된 텐서는 기본적으로 float32 데이터 타입을 가진다.
PyTorch는 실수(float)를 기본 데이터 타입으로 사용한다.
따라서, 값 1.은 실수를 의미하며, 소숫점이 없는 정수 1과 구분된다.

텐서 합치기 torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다.

In [22]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


산술 연산(Arithmetic operations)

In [29]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환합니다.
y1 = tensor @ tensor.T #@는 행렬곱 연산자.  tensor @ tensor.T는 4ㅌ4 행렬 텐서와 그 저ㄴ치 행렬 텐서.T의 행렬곱을 계
y2 = tensor.matmul(tensor.T) #tensor.matmul()은 PyTorch에서 행렬 곱을 수행하는 메서드

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) #out 매개변수를 사용하여 결과를 저장할 텐서를 지정


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
#요소별 곱은 두 텐서의 동일한 위치에 있는 요소를 곱하는 연산
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

단일-요소(single-element) 텐서 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:

In [30]:
agg = tensor.sum() #텐서의 모든 요소를 더한 값을 반환
agg_item = agg.item() #스칼라 텐서를 기본 데이터타입으로 변환
print(agg_item, type(agg_item))

12.0 <class 'float'>


바꿔치기(in-place) 연산 연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, _ 접미사를 갖습니다. 예를 들어: x.copy_(y) 나 x.t_() 는 x 를 변경합니다.

In [31]:
print(f"{tensor} \n")
tensor.add_(5) # 모든 요소에 5를 더하는 연산
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서, 사용을 권장하지 않습니다.

**NumPy 변환(Bridge)**

텐서를 NumPy 배열로 변환하기

In [32]:
t = torch.ones(5) #크기가 5인 1차원 텐서를 생성. 생성된 텐서의 모든 값은 1로 초기화
print(f"t: {t}")
n = t.numpy() #텐서를 NumPy 배열로 변환
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영됩니다.

In [33]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy 배열을 텐서로 변환하기

In [34]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영됩니다.

In [35]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
